name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: validate types
        run: npm run validate-types
      - name: tests
        run: npm run test
  publish:
    runs-on: ubuntu-latest
    needs: build
    # if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: install dependencies
        run: npm ci
      - name: check version
        run: echo "Package version $(awk -F'"' '/"version": ".+"/{ print $4; exit; }' package.json)"
